### ISSUE TITLE
Dataset Download links dead

### ISSUE THREAD

**Issue by dennisritter** [yifanfeng97/multi-modal-generation-for-shrec22#1]
Hello,

the download links for the two datasets **OS-MN40** and **OS-MN40-MISS** are not working. Could you send me updated links or check the current ones, please? Thanks in advance!
Dennis

**Comment by yifanfeng97** [comment]
Maybe the unstable network. The link is working well now. ^_^

**Comment by yifanfeng97** [comment]
OS-MN40: https://data.shrec22.moon-lab.tech:18443/SHREC22/OS-MN40.tar.gz
OS-MN40-Miss: https://data.shrec22.moon-lab.tech:18443/SHREC22/OS-MN40-Miss.tar.gz
